# Generated by Django 5.2.5 on 2025-09-01 20:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.comuna')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion')),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Bibliotecas',
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido', regex='^\\d{7,8}-[0-9kK]$')])),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField(default=True)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion')),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('paginas', models.PositiveIntegerField()),
                ('copias', models.PositiveIntegerField(default=1)),
                ('habilitado', models.BooleanField(default=True)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.nacionalidad'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('plazo_devolucion', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
    ]
